author: Olloth
authors: [Olloth]
database: false
description: Flight for Spout
main: me.olloth.plugins.flight.SpoutFlight
name: SpoutFlight
startup: postworld
version: '1.4'
depend: [Spout]
permissions:
    spoutflight.fly:
        default: false
    spoutflight.nofalldmg:
        default: false
commands:
    sfspeed:
     description: Sets your flying speed
     usage: /<command> [speed 1-max speed]
     aliases: [fly]
     permission: spoutflight.fly
    sfbind:
     description: Sets your keybind for flying
     aliases: [flybind]
     usage: /<command>
     permission: spoutflight.fly
